### ISSUE TITLE
Support for resolving typed lists with ContainerBuilder 

### ISSUE THREAD

**Issue by ticdenis** [ticdenis/python-aiodi#10]
This is currently not possible and it would be great if examples like the following could work.

```python
class UserPermission:
  pass

def default_user_permissions() -> list[UserPermission]:
  return [UserPermission()]

class UserHandler:
  __slots__  = '_permissions'
  
  def __init__(self, permissions: list[UserPermission]) -> None:
    self._permissions = permissions 
```

```toml
[tool.aiodi.services."default_user_permissions"]
class = "sample.default_user_permissions"

[tool.aiodi.services."UserHandler"]
class = "sample.UserHandler" # <- this will fails because library does not inspect list type.
```
