### ISSUE TITLE
Supports multiple casting for variables using ContainerBuilder

### ISSUE THREAD

**Issue by ticdenis** [ticdenis/python-aiodi#5]
Currently we have 3 options to cast variables using the ContainerBuilder:

```toml
# pyproject.toml

[tool.aiodi.variables]
# Get static text.
debug = "Text"
# Get as str a variable.
debug2 = "%var(debug)%"
# Cast to int an environment variable.
debug3 = "%env(int:APP_DEBUG, '1')%"
```

But we can not do:

```toml
# pyproject.toml

[tool.aiodi.variables]
# ...
debug4 = "%env(bool:int:APP_DEBUG, '1')%"
```

We've detected that this is a common operation so would be great have it integrate it on ContainerBuilder.
